DELETE DATABASE smarthome
CREATE DATABASE smarthome
USE smarthome

create table users (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR (50) NOT NULL,
    email VARCHAR (255) UNIQUE NOT NULL,
    role ENUM('user', 'admin') DEFAULT 'user' NOT NULL,
    password VARCHAR (255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP DEFAULT NULL
)ENGINE=INNODB DEFAULT COLLATE UTF8_GENERAL_CI;
 
CREATE TABLE access_tokens (
    user_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    token VARCHAR(20) BINARY NOT NULL,
    role ENUM('user', 'customeradmin', 'admin') NOT NULL,
    expires_at TIMESTAMP NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)ENGINE=INNODB DEFAULT COLLATE UTF8_GENERAL_CI;